#!/usr/bin/env bash
#a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
until [ $n -gt 10 ]
do 
  echo "Best School"
  ((n++))
done
