#!/usr/bin/env bash

# Initialize the counter
n=1

# Loop until n is 10
while [ $n -le 10 ]
do
  echo "Best School"  # Print "Best School" each time

  # On the 9th iteration, print "Hi"
  if [ $n -eq 9 ]; then
    echo "Hi"
  fi

  ((n++))  # Increment the counter
done
